# Generated by Django 3.2 on 2022-04-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_tool_limit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ImageField(null=True, upload_to='image', verbose_name='工具图片'),
        ),
        migrations.AddField(
            model_name='label',
            name='portrait',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='图片路径url'),
        ),
    ]
