# Generated by Django 3.2 on 2022-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20220411_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrequest',
            name='address',
            field=models.CharField(default=None, max_length=1000, verbose_name='取件地点'),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='date_endTime',
            field=models.CharField(default=None, max_length=1000, verbose_name='取件结束时间'),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='date_startTime',
            field=models.CharField(default=None, max_length=1000, verbose_name='取件开始时间'),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='get_date',
            field=models.CharField(default=None, max_length=1000, verbose_name='取件日期'),
        ),
    ]
