# Generated by Django 4.1.5 on 2023-01-08 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('tool', '0005_auto_20220509_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepealPostpone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='提交延期申请时间')),
                ('Status', models.CharField(choices=[('W', 'Wait'), ('A', 'Accept'), ('R', 'Refuse'), ('F', 'Finish')], default='W', max_length=1, verbose_name='审批情况')),
                ('refuseReason', models.CharField(default=None, max_length=1000, null=True, verbose_name='拒绝里有')),
                ('purpose', models.CharField(default=None, max_length=1000, null=True, verbose_name='原因')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RepealRequest', to='tool.toolrequest')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RepealRequest', to='user.user')),
            ],
            options={
                'ordering': ['-request_time'],
            },
        ),
    ]
