# Generated by Django 4.1.5 on 2023-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oid',
            field=models.CharField(max_length=1000, null=True, verbose_name='微信id'),
        ),
    ]
