# Generated by Django 4.2 on 2024-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_userregisterrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
