# Generated by Django 4.2 on 2024-09-04 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="acc",
            new_name="email",
        ),
    ]
