# Generated by Django 4.2 on 2024-09-04 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_rename_acc_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="acc",
        ),
    ]
