# Generated by Django 4.2 on 2024-09-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_rename_email_user_acc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailrecord",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
