# Generated by Django 3.2 on 2022-03-28 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='验证码')),
                ('acc', models.EmailField(default='', max_length=50, null=True, verbose_name='用户邮箱')),
                ('send_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发送时间')),
                ('email_type', models.CharField(choices=[('register', '注册邮件'), ('forget', '找回密码')], max_length=10)),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.EmailField(max_length=96, null=True, unique=True, verbose_name='账号')),
                ('pwd', models.CharField(max_length=96, null=True, verbose_name='密码')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='姓名')),
                ('studentId', models.CharField(max_length=256, null=True, verbose_name='学号')),
                ('college', models.CharField(max_length=1024, null=True, verbose_name='学院')),
                ('phoneNumber', models.CharField(max_length=256, null=True, verbose_name='学号')),
            ],
        ),
    ]
