# Generated by Django 3.2 on 2022-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='limit_days',
            field=models.IntegerField(default=1000, verbose_name='现有可用工具数量'),
        ),
    ]
