# Generated by Django 4.2 on 2024-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tool", "0006_repealpostpone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="repealpostpone",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="requestpostpone",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tool",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="toolrequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
