# Generated by Django 4.2 on 2024-09-04 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_rename_acc_manager_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manager",
            old_name="email",
            new_name="acc",
        ),
    ]
